name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        ruby_version: [2.5, 2.6, 2.7, 3.0]
        experimental: [false]
        include:
          - ruby_version: head
            os: ubuntu-latest
            experimental: true
    env:
      LANG: en_US.UTF-8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{  matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install --jobs 4 --retry 3
    - name: Run test
      run: |
        bundle exec rake
